### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by mythodeia** [ideaismobile/AKLocationManager#5]
Hello and thanks for your code

i think in the 
- (void)startLocatingWithUpdateBlock:(LocationUpdateBlock)didUpdate failedBlock:(LocationFailedBlock)didFail
  method the _locationTimeoutTimer should be 
  [NSTimer scheduledTimerWithTimeInterval:_timeoutTimeInterval ....
  and not 
  [NSTimer scheduledTimerWithTimeInterval:10

this way it respects the user's choice when setting the timeout like this:
[AKLocationManager setTimeoutTimeInterval:2];

thanks

**Comment by thiagoperes** [comment]
1.0.2 fixes this. Thank you!
